

     /**
 * Main JSON object of posts, pages and settings
 */
var posts = [
      {
        "id":1,
        "text":"<h1>Personal Profile Page</h1><p>Redeye trifecta pumpkin spice roast turkish, black, coffee in, caramelization aroma, mocha grounds single shot carajillo pumpkin spice sugar. Cinnamon, affogato acerbic cream, sugar crema steamed, flavour strong doppio single shot beans siphon kopi-luwak acerbic shop, id, crema variety french press to go aroma aged. Siphon viennese, whipped sugar trifecta cup and, shop siphon, java, roast, crema shop, organic arabica robust cortado half and half a espresso as breve. Frappuccino brewed mocha, single shot caffeine mocha french press aftertaste siphon trifecta, wings extraction robusta cream decaffeinated, crema, plunger pot fair trade kopi-luwak milk single shot brewed coffee saucer. Pumpkin spice, blue mountain frappuccino redeye caffeine, aged milk latte seasonal et, turkish single shot seasonal wings shop, brewed seasonal and coffee black affogato. Lungo in ristretto blue mountain, iced beans brewed, seasonal, decaffeinated, flavour acerbic rich et so spoon decaffeinated robust saucer espresso so aroma cream mazagran. Coffee, whipped in so, plunger pot organic, spoon sit as iced, aromatic percolator macchiato aroma extraction froth sugar breve irish. Black, </p><h4>Some tools and Methods used:</h4></h4<ul><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li</ul>"

      },
      {
        "id":2,
        "text":"<h1>Online Registration Form</h1><p>Redeye trifecta pumpkin spice roast turkish, black, coffee in, caramelization aroma, mocha grounds single shot carajillo pumpkin spice sugar. Cinnamon, affogato acerbic cream, sugar crema steamed, flavour strong doppio single shot beans siphon kopi-luwak acerbic shop, id, crema variety french press to go aroma aged. Siphon viennese, whipped sugar trifecta cup and, shop siphon, java, roast, crema shop, organic arabica robust cortado half and half a espresso as breve. Frappuccino brewed mocha, single shot caffeine mocha french press aftertaste siphon trifecta, wings extraction robusta cream decaffeinated, crema, plunger pot fair trade kopi-luwak milk single shot brewed coffee saucer. Pumpkin spice, blue mountain frappuccino redeye caffeine, aged milk latte seasonal et, turkish single shot seasonal wings shop, brewed seasonal and coffee black affogato. Lungo in ristretto blue mountain, iced beans brewed, seasonal, decaffeinated, flavour acerbic rich et so spoon decaffeinated robust saucer espresso so aroma cream mazagran. Coffee, whipped in so, plunger pot organic, spoon sit as iced, aromatic percolator macchiato aroma extraction froth sugar breve irish. Black, </p><h4>Some tools and Methods used:</h4></h4<ul><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li</ul>"


      },
      {
        "id":3,
        "text":"<h1>Interactive Photo Gallery</h1><p>Redeye trifecta pumpkin spice roast turkish, black, coffee in, caramelization aroma, mocha grounds single shot carajillo pumpkin spice sugar. Cinnamon, affogato acerbic cream, sugar crema steamed, flavour strong doppio single shot beans siphon kopi-luwak acerbic shop, id, crema variety french press to go aroma aged. Siphon viennese, whipped sugar trifecta cup and, shop siphon, java, roast, crema shop, organic arabica robust cortado half and half a espresso as breve. Frappuccino brewed mocha, single shot caffeine mocha french press aftertaste siphon trifecta, wings extraction robusta cream decaffeinated, crema, plunger pot fair trade kopi-luwak milk single shot brewed coffee saucer. Pumpkin spice, blue mountain frappuccino redeye caffeine, aged milk latte seasonal et, turkish single shot seasonal wings shop, brewed seasonal and coffee black affogato. Lungo in ristretto blue mountain, iced beans brewed, seasonal, decaffeinated, flavour acerbic rich et so spoon decaffeinated robust saucer espresso so aroma cream mazagran. Coffee, whipped in so, plunger pot organic, spoon sit as iced, aromatic percolator macchiato aroma extraction froth sugar breve irish. Black, </p><h4>Some tools and Methods used:</h4></h4<ul><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li</ul>"

      },
      {
        "id":4,
        "text":"<h1>FireBug Music</h1><p>Redeye trifecta pumpkin spice roast turkish, black, coffee in, caramelization aroma, mocha grounds single shot carajillo pumpkin spice sugar. Cinnamon, affogato acerbic cream, sugar crema steamed, flavour strong doppio single shot beans siphon kopi-luwak acerbic shop, id, crema variety french press to go aroma aged. Siphon viennese, whipped sugar trifecta cup and, shop siphon, java, roast, crema shop, organic arabica robust cortado half and half a espresso as breve. Frappuccino brewed mocha, single shot caffeine mocha french press aftertaste siphon trifecta, wings extraction robusta cream decaffeinated, crema, plunger pot fair trade kopi-luwak milk single shot brewed coffee saucer. Pumpkin spice, blue mountain frappuccino redeye caffeine, aged milk latte seasonal et, turkish single shot seasonal wings shop, brewed seasonal and coffee black affogato. Lungo in ristretto blue mountain, iced beans brewed, seasonal, decaffeinated, flavour acerbic rich et so spoon decaffeinated robust saucer espresso so aroma cream mazagran. Coffee, whipped in so, plunger pot organic, spoon sit as iced, aromatic percolator macchiato aroma extraction froth sugar breve irish. Black, </p><h4>Some tools and Methods used:</h4></h4<ul><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li</ul>"
      },

      {
        "id":5,
        "text":"<h1>SVG Site Update</h1><p>Redeye trifecta pumpkin spice roast turkish, black, coffee in, caramelization aroma, mocha grounds single shot carajillo pumpkin spice sugar. Cinnamon, affogato acerbic cream, sugar crema steamed, flavour strong doppio single shot beans siphon kopi-luwak acerbic shop, id, crema variety french press to go aroma aged. Siphon viennese, whipped sugar trifecta cup and, shop siphon, java, roast, crema shop, organic arabica robust cortado half and half a espresso as breve. Frappuccino brewed mocha, single shot caffeine mocha french press aftertaste siphon trifecta, wings extraction robusta cream decaffeinated, crema, plunger pot fair trade kopi-luwak milk single shot brewed coffee saucer. Pumpkin spice, blue mountain frappuccino redeye caffeine, aged milk latte seasonal et, turkish single shot seasonal wings shop, brewed seasonal and coffee black affogato. Lungo in ristretto blue mountain, iced beans brewed, seasonal, decaffeinated, flavour acerbic rich et so spoon decaffeinated robust saucer espresso so aroma cream mazagran. Coffee, whipped in so, plunger pot organic, spoon sit as iced, aromatic percolator macchiato aroma extraction froth sugar breve irish. Black, </p><h4>Some tools and Methods used:</h4></h4<ul><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li</ul>"

      },
      {
        "id":6,
        "text":"<h1>Interactive Video Player</h1><p>Redeye trifecta pumpkin spice roast turkish, black, coffee in, caramelization aroma, mocha grounds single shot carajillo pumpkin spice sugar. Cinnamon, affogato acerbic cream, sugar crema steamed, flavour strong doppio single shot beans siphon kopi-luwak acerbic shop, id, crema variety french press to go aroma aged. Siphon viennese, whipped sugar trifecta cup and, shop siphon, java, roast, crema shop, organic arabica robust cortado half and half a espresso as breve. Frappuccino brewed mocha, single shot caffeine mocha french press aftertaste siphon trifecta, wings extraction robusta cream decaffeinated, crema, plunger pot fair trade kopi-luwak milk single shot brewed coffee saucer. Pumpkin spice, blue mountain frappuccino redeye caffeine, aged milk latte seasonal et, turkish single shot seasonal wings shop, brewed seasonal and coffee black affogato. Lungo in ristretto blue mountain, iced beans brewed, seasonal, decaffeinated, flavour acerbic rich et so spoon decaffeinated robust saucer espresso so aroma cream mazagran. Coffee, whipped in so, plunger pot organic, spoon sit as iced, aromatic percolator macchiato aroma extraction froth sugar breve irish. Black, </p><h4>Some tools and Methods used:</h4></h4<ul><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li</ul>"

      },
      {
        "id":7,
        "text":"<h1>Accessibility Refactor</h1><p>Redeye trifecta pumpkin spice roast turkish, black, coffee in, caramelization aroma, mocha grounds single shot carajillo pumpkin spice sugar. Cinnamon, affogato acerbic cream, sugar crema steamed, flavour strong doppio single shot beans siphon kopi-luwak acerbic shop, id, crema variety french press to go aroma aged. Siphon viennese, whipped sugar trifecta cup and, shop siphon, java, roast, crema shop, organic arabica robust cortado half and half a espresso as breve. Frappuccino brewed mocha, single shot caffeine mocha french press aftertaste siphon trifecta, wings extraction robusta cream decaffeinated, crema, plunger pot fair trade kopi-luwak milk single shot brewed coffee saucer. Pumpkin spice, blue mountain frappuccino redeye caffeine, aged milk latte seasonal et, turkish single shot seasonal wings shop, brewed seasonal and coffee black affogato. Lungo in ristretto blue mountain, iced beans brewed, seasonal, decaffeinated, flavour acerbic rich et so spoon decaffeinated robust saucer espresso so aroma cream mazagran. Coffee, whipped in so, plunger pot organic, spoon sit as iced, aromatic percolator macchiato aroma extraction froth sugar breve irish. Black, </p><h4>Some tools and Methods used:</h4></h4<ul><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li</ul>"

      },
      {
        "id":8,
        "text":"<h1>Web APP Dashboard</h1><p>Redeye trifecta pumpkin spice roast turkish, black, coffee in, caramelization aroma, mocha grounds single shot carajillo pumpkin spice sugar. Cinnamon, affogato acerbic cream, sugar crema steamed, flavour strong doppio single shot beans siphon kopi-luwak acerbic shop, id, crema variety french press to go aroma aged. Siphon viennese, whipped sugar trifecta cup and, shop siphon, java, roast, crema shop, organic arabica robust cortado half and half a espresso as breve. Frappuccino brewed mocha, single shot caffeine mocha french press aftertaste siphon trifecta, wings extraction robusta cream decaffeinated, crema, plunger pot fair trade kopi-luwak milk single shot brewed coffee saucer. Pumpkin spice, blue mountain frappuccino redeye caffeine, aged milk latte seasonal et, turkish single shot seasonal wings shop, brewed seasonal and coffee black affogato. Lungo in ristretto blue mountain, iced beans brewed, seasonal, decaffeinated, flavour acerbic rich et so spoon decaffeinated robust saucer espresso so aroma cream mazagran. Coffee, whipped in so, plunger pot organic, spoon sit as iced, aromatic percolator macchiato aroma extraction froth sugar breve irish. Black, </p><h4>Some tools and Methods used:</h4></h4<ul><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li</ul>"

      },
      {
        "id":9,
        "text":"<h1>Public API</h1><p>Redeye trifecta pumpkin spice roast turkish, black, coffee in, caramelization aroma, mocha grounds single shot carajillo pumpkin spice sugar. Cinnamon, affogato acerbic cream, sugar crema steamed, flavour strong doppio single shot beans siphon kopi-luwak acerbic shop, id, crema variety french press to go aroma aged. Siphon viennese, whipped sugar trifecta cup and, shop siphon, java, roast, crema shop, organic arabica robust cortado half and half a espresso as breve. Frappuccino brewed mocha, single shot caffeine mocha french press aftertaste siphon trifecta, wings extraction robusta cream decaffeinated, crema, plunger pot fair trade kopi-luwak milk single shot brewed coffee saucer. Pumpkin spice, blue mountain frappuccino redeye caffeine, aged milk latte seasonal et, turkish single shot seasonal wings shop, brewed seasonal and coffee black affogato. Lungo in ristretto blue mountain, iced beans brewed, seasonal, decaffeinated, flavour acerbic rich et so spoon decaffeinated robust saucer espresso so aroma cream mazagran. Coffee, whipped in so, plunger pot organic, spoon sit as iced, aromatic percolator macchiato aroma extraction froth sugar breve irish. Black, </p><h4>Some tools and Methods used:</h4></h4<ul><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li</ul>"

      },
      {
        "id":10,
        "text":"<h1>Web Optimization</h1><p>Performance_Optimization Apply the skills learned for optimization of graphics, HTML, CSS, and JavaScript to take a poorly optimized site and reduce the total load size to under 1.3mb and total requests to less than 27. Students will need to analyze the assets they've been provided to see where optimizations can and need to be made, make those optimizations, and measure their success. Multiple analyzation, optimization, and measuring cycles may be required.</p><h4>Some tools and Methods used:</h4></h4<ul><li>-Google page speed +  node phantomas/http-server via npm start in command line to test in separate testing directory on desktop</li><li>-Gulp imagesOpt and gulp images for image optimization that were then piped from the src development directory to the dist production directory</li><li>-Gulp minifyHTML, minifyCSS, Gulp Watch, Gulp connect, Gulp concatScripts, Gulp build (for automation) and more..</li</ul>",

      },
      {
        "id":11,
        "text":"<h1>CSS to Sass</h1><p>Redeye trifecta pumpkin spice roast turkish, black, coffee in, caramelization aroma, mocha grounds single shot carajillo pumpkin spice sugar. Cinnamon, affogato acerbic cream, sugar crema steamed, flavour strong doppio single shot beans siphon kopi-luwak acerbic shop, id, crema variety french press to go aroma aged. Siphon viennese, whipped sugar trifecta cup and, shop siphon, java, roast, crema shop, organic arabica robust cortado half and half a espresso as breve. Frappuccino brewed mocha, single shot caffeine mocha french press aftertaste siphon trifecta, wings extraction robusta cream decaffeinated, crema, plunger pot fair trade kopi-luwak milk single shot brewed coffee saucer. Pumpkin spice, blue mountain frappuccino redeye caffeine, aged milk latte seasonal et, turkish single shot seasonal wings shop, brewed seasonal and coffee black affogato. Lungo in ristretto blue mountain, iced beans brewed, seasonal, decaffeinated, flavour acerbic rich et so spoon decaffeinated robust saucer espresso so aroma cream mazagran. Coffee, whipped in so, plunger pot organic, spoon sit as iced, aromatic percolator macchiato aroma extraction froth sugar breve irish. Black, </p><h4>Some tools and Methods used:</h4></h4<ul><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li><li>-percolator macchiato aroma extraction froth sugar breve irish. Black,</li</ul>"

      },
    ],
     jsonData = JSON.stringify( posts );
